name: swifty_companion
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  flutter_dotenv: ^5.1.0
  cupertino_icons: ^1.0.2
  flutter_web_auth_2: ^5.0.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/42_Icon.png"
  min_sdk_android: 21

  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/42_Icon.png"

flutter_native_splash:
  color: "#000000"
  image: "assets/images/42_Splash.png"
  fullscreen: true
  android_12:
    color: "#000000"
    image: "assets/images/42_Splash.png"